name: 'fintech_analytics'
version: '1.0.0'
config-version: 2

profile: 'fintech_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  fintech_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      fraud_detection:
        +materialized: table
        +schema: fraud_detection
      revenue_analysis:
        +materialized: table
        +schema: revenue_analysis

vars:
  # Add any project-level variables here
  start_date: '2024-01-01'
  end_date: '2024-12-31' 